/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import business_logic.Controller;
import carrentalsystem.Customer;
import carrentalsystem.Rental;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author William J. Freeman
 */
public class RentalInfo extends javax.swing.JFrame {
    private Controller controller;
    /**
     * Creates new form RentalInfo
     */
    public RentalInfo(String custName, int tabNum) {
        controller = Controller.instance();
        initComponents();
        jTabbedPane1.setSelectedIndex(tabNum);
        customerNameText.setText(custName);
        
        DefaultTableModel rentedCarsModel = (DefaultTableModel) rentedCarsTable.getModel();
        rentedCarsModel.setNumRows(0);
        LinkedList<String[]> rentedCars = controller.searchRentedCars());
        for(String[] customer:customers){
            custModel.addRow(customer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerNameText = new javax.swing.JLabel();
        accountText = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        findCarPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        rentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rentCarTable = new javax.swing.JTable();
        rentedCarsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rentedCarsTable = new javax.swing.JTable();
        returnButton = new javax.swing.JButton();
        returnedCarsPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        returnedCarsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        customerNameText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerNameText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customerNameText.setText("Name");

        accountText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        accountText.setLabelFor(customerNameText);
        accountText.setText("Account:");

        searchButton.setText("Search");
        searchButton.setToolTipText("");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        rentButton.setText("Rent Selected");
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });

        rentCarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "ID", "Make", "Model", "Year", "Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rentCarTable);

        javax.swing.GroupLayout findCarPanelLayout = new javax.swing.GroupLayout(findCarPanel);
        findCarPanel.setLayout(findCarPanelLayout);
        findCarPanelLayout.setHorizontalGroup(
            findCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findCarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(findCarPanelLayout.createSequentialGroup()
                        .addGroup(findCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(findCarPanelLayout.createSequentialGroup()
                                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton))
                            .addComponent(rentButton))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        findCarPanelLayout.setVerticalGroup(
            findCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findCarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Find Car", findCarPanel);

        rentedCarsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "Make", "Model", "Year", "Rented"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(rentedCarsTable);

        returnButton.setText("Return Selected");

        javax.swing.GroupLayout rentedCarsPanelLayout = new javax.swing.GroupLayout(rentedCarsPanel);
        rentedCarsPanel.setLayout(rentedCarsPanelLayout);
        rentedCarsPanelLayout.setHorizontalGroup(
            rentedCarsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentedCarsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rentedCarsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addGroup(rentedCarsPanelLayout.createSequentialGroup()
                        .addComponent(returnButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rentedCarsPanelLayout.setVerticalGroup(
            rentedCarsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentedCarsPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rented Cars", rentedCarsPanel);

        returnedCarsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Make", "Model", "Year", "Rented", "Returned"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(returnedCarsTable);

        javax.swing.GroupLayout returnedCarsPanelLayout = new javax.swing.GroupLayout(returnedCarsPanel);
        returnedCarsPanel.setLayout(returnedCarsPanelLayout);
        returnedCarsPanelLayout.setHorizontalGroup(
            returnedCarsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnedCarsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );
        returnedCarsPanelLayout.setVerticalGroup(
            returnedCarsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnedCarsPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Returned Cars", returnedCarsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accountText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerNameText)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountText)
                    .addComponent(customerNameText))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tab1\n");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        DefaultTableModel carModel = (DefaultTableModel) rentCarTable.getModel();
        carModel.setNumRows(0);
        LinkedList<String[]> cars = controller.searchCars(searchTextField.getText());
        for(String[] car:cars){
            carModel.addRow(new Object[]{false, car[0], car[1], car[2], car[3], 
                car[4]});
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed

        int totalRows = rentCarTable.getRowCount();
        for (int row=0; row < totalRows; row++) {
            if ((Boolean)rentCarTable.getValueAt(row, 0)) {
                controller.addRental((String)rentCarTable.getValueAt(row, 1), customerNameText.getText());
            }
        }
    }//GEN-LAST:event_rentButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountText;
    private javax.swing.JLabel customerNameText;
    private javax.swing.JPanel findCarPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton rentButton;
    private javax.swing.JTable rentCarTable;
    private javax.swing.JPanel rentedCarsPanel;
    private javax.swing.JTable rentedCarsTable;
    private javax.swing.JButton returnButton;
    private javax.swing.JPanel returnedCarsPanel;
    private javax.swing.JTable returnedCarsTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
